-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
-- Version: 2021.1
-- Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity eucDis_sqrt_fixed_27_27_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    x : IN STD_LOGIC_VECTOR (25 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (13 downto 0) );
end;


architecture behav of eucDis_sqrt_fixed_27_27_s is 
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_19 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011001";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv3_7 : STD_LOGIC_VECTOR (2 downto 0) := "111";
    constant ap_const_lv32_1B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011011";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_16 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010110";
    constant ap_const_lv32_1A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011010";
    constant ap_const_lv14_0 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000000";
    constant ap_const_lv14_1000 : STD_LOGIC_VECTOR (13 downto 0) := "01000000000000";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_12 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010010";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_15 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010101";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010011";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_11 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010001";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv14_1 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000001";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';

attribute shreg_extract : string;
    signal icmp_ln489_fu_202_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln489_reg_1203 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter5 : BOOLEAN;
    signal ap_block_state7_pp0_stage0_iter6 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal x_l_I_V_25_fu_230_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal x_l_I_V_25_reg_1208 : STD_LOGIC_VECTOR (29 downto 0);
    signal icmp_ln489_1_fu_268_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln489_1_reg_1214 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln258_fu_274_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal sub_ln258_reg_1220 : STD_LOGIC_VECTOR (4 downto 0);
    signal x_l_I_V_27_fu_386_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal x_l_I_V_27_reg_1225 : STD_LOGIC_VECTOR (29 downto 0);
    signal res_I_V_26_fu_394_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal res_I_V_26_reg_1231 : STD_LOGIC_VECTOR (13 downto 0);
    signal icmp_ln489_3_fu_434_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln489_3_reg_1237 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln258_2_fu_440_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal sub_ln258_2_reg_1243 : STD_LOGIC_VECTOR (6 downto 0);
    signal x_l_I_V_29_fu_543_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal x_l_I_V_29_reg_1248 : STD_LOGIC_VECTOR (29 downto 0);
    signal res_I_V_28_fu_551_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal res_I_V_28_reg_1254 : STD_LOGIC_VECTOR (13 downto 0);
    signal icmp_ln489_5_fu_591_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln489_5_reg_1260 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln258_4_fu_597_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal sub_ln258_4_reg_1266 : STD_LOGIC_VECTOR (8 downto 0);
    signal x_l_I_V_30_fu_700_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal x_l_I_V_30_reg_1271 : STD_LOGIC_VECTOR (29 downto 0);
    signal res_I_V_fu_708_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal res_I_V_reg_1277 : STD_LOGIC_VECTOR (13 downto 0);
    signal icmp_ln489_7_fu_748_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln489_7_reg_1283 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln258_6_fu_754_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal sub_ln258_6_reg_1289 : STD_LOGIC_VECTOR (10 downto 0);
    signal x_l_I_V_32_fu_857_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal x_l_I_V_32_reg_1294 : STD_LOGIC_VECTOR (29 downto 0);
    signal res_I_V_31_fu_865_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal res_I_V_31_reg_1300 : STD_LOGIC_VECTOR (13 downto 0);
    signal icmp_ln489_9_fu_905_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln489_9_reg_1306 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln258_8_fu_911_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal sub_ln258_8_reg_1312 : STD_LOGIC_VECTOR (12 downto 0);
    signal x_l_I_V_34_fu_1014_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal x_l_I_V_34_reg_1317 : STD_LOGIC_VECTOR (29 downto 0);
    signal res_I_V_33_fu_1022_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal res_I_V_33_reg_1323 : STD_LOGIC_VECTOR (13 downto 0);
    signal icmp_ln489_11_fu_1062_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln489_11_reg_1329 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln258_10_fu_1068_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal sub_ln258_10_reg_1335 : STD_LOGIC_VECTOR (14 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal tmp_fu_188_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln489_12_fu_198_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln258_fu_208_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal zext_ln712_fu_184_p1 : STD_LOGIC_VECTOR (29 downto 0);
    signal sext_ln323_fu_214_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal p_Result_38_fu_218_p5 : STD_LOGIC_VECTOR (29 downto 0);
    signal select_ln489_fu_238_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_2_fu_246_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal p_Result_5_fu_254_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln489_fu_264_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal select_ln239_fu_280_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal p_Result_39_fu_287_p5 : STD_LOGIC_VECTOR (29 downto 0);
    signal p_Result_40_fu_297_p4 : STD_LOGIC_VECTOR (13 downto 0);
    signal res_I_V_25_fu_313_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal p_Result_8_fu_320_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal x_l_I_V_26_fu_307_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal tmp_3_fu_330_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal p_Result_9_fu_338_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln489_1_fu_348_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal sub_ln258_1_fu_358_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal icmp_ln489_2_fu_352_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_41_fu_364_p5 : STD_LOGIC_VECTOR (29 downto 0);
    signal p_Result_42_fu_376_p4 : STD_LOGIC_VECTOR (13 downto 0);
    signal p_Result_s_fu_402_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_4_fu_412_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal p_Result_1_fu_420_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln489_2_fu_430_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal p_Result_43_fu_446_p5 : STD_LOGIC_VECTOR (29 downto 0);
    signal p_Result_44_fu_456_p4 : STD_LOGIC_VECTOR (13 downto 0);
    signal res_I_V_27_fu_471_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal p_Result_6_fu_477_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal x_l_I_V_28_fu_465_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal tmp_5_fu_487_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal p_Result_7_fu_495_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln489_3_fu_505_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal sub_ln258_3_fu_515_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln489_4_fu_509_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_45_fu_521_p5 : STD_LOGIC_VECTOR (29 downto 0);
    signal p_Result_46_fu_533_p4 : STD_LOGIC_VECTOR (13 downto 0);
    signal p_Result_12_fu_559_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_6_fu_569_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_Result_13_fu_577_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln489_4_fu_587_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_Result_47_fu_603_p5 : STD_LOGIC_VECTOR (29 downto 0);
    signal p_Result_48_fu_613_p4 : STD_LOGIC_VECTOR (13 downto 0);
    signal res_I_V_29_fu_628_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal p_Result_15_fu_634_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal x_l_I_V_fu_622_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal tmp_7_fu_644_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_Result_16_fu_652_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln489_5_fu_662_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal sub_ln258_5_fu_672_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln489_6_fu_666_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_49_fu_678_p5 : STD_LOGIC_VECTOR (29 downto 0);
    signal p_Result_50_fu_690_p4 : STD_LOGIC_VECTOR (13 downto 0);
    signal p_Result_18_fu_716_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_8_fu_726_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_Result_19_fu_734_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln489_6_fu_744_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal p_Result_51_fu_760_p5 : STD_LOGIC_VECTOR (29 downto 0);
    signal p_Result_52_fu_770_p4 : STD_LOGIC_VECTOR (13 downto 0);
    signal res_I_V_30_fu_785_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal p_Result_21_fu_791_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal x_l_I_V_31_fu_779_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal tmp_9_fu_801_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal p_Result_22_fu_809_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln489_7_fu_819_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal sub_ln258_7_fu_829_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal icmp_ln489_8_fu_823_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_53_fu_835_p5 : STD_LOGIC_VECTOR (29 downto 0);
    signal p_Result_54_fu_847_p4 : STD_LOGIC_VECTOR (13 downto 0);
    signal p_Result_24_fu_873_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_s_fu_883_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal p_Result_25_fu_891_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal zext_ln489_8_fu_901_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal p_Result_55_fu_917_p5 : STD_LOGIC_VECTOR (29 downto 0);
    signal p_Result_56_fu_927_p4 : STD_LOGIC_VECTOR (13 downto 0);
    signal res_I_V_32_fu_942_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal p_Result_27_fu_948_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal x_l_I_V_33_fu_936_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal tmp_1_fu_958_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal p_Result_28_fu_966_p4 : STD_LOGIC_VECTOR (13 downto 0);
    signal zext_ln489_9_fu_976_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal sub_ln258_9_fu_986_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal icmp_ln489_10_fu_980_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_57_fu_992_p5 : STD_LOGIC_VECTOR (29 downto 0);
    signal p_Result_58_fu_1004_p4 : STD_LOGIC_VECTOR (13 downto 0);
    signal p_Result_30_fu_1030_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_10_fu_1040_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal p_Result_31_fu_1048_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal zext_ln489_10_fu_1058_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal p_Result_59_fu_1074_p5 : STD_LOGIC_VECTOR (29 downto 0);
    signal p_Result_60_fu_1084_p4 : STD_LOGIC_VECTOR (13 downto 0);
    signal res_I_V_34_fu_1099_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal x_l_I_V_35_fu_1093_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal tmp_11_fu_1105_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln640_fu_1113_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln489_11_fu_1117_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sub_ln258_11_fu_1127_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln489_12_fu_1121_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_61_fu_1133_p5 : STD_LOGIC_VECTOR (29 downto 0);
    signal p_Result_62_fu_1145_p4 : STD_LOGIC_VECTOR (13 downto 0);
    signal res_I_V_35_fu_1163_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal mul_I_V_fu_1171_p3 : STD_LOGIC_VECTOR (27 downto 0);
    signal x_l_I_V_36_fu_1155_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal zext_ln717_fu_1179_p1 : STD_LOGIC_VECTOR (29 downto 0);
    signal p_Result_s_53_fu_1183_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal res_I_V_23_fu_1189_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal x_int_reg : STD_LOGIC_VECTOR (25 downto 0);
    signal ap_ce_reg : STD_LOGIC;


begin




    x_int_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            x_int_reg <= x;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                icmp_ln489_11_reg_1329 <= icmp_ln489_11_fu_1062_p2;
                icmp_ln489_1_reg_1214 <= icmp_ln489_1_fu_268_p2;
                icmp_ln489_3_reg_1237 <= icmp_ln489_3_fu_434_p2;
                icmp_ln489_5_reg_1260 <= icmp_ln489_5_fu_591_p2;
                icmp_ln489_7_reg_1283 <= icmp_ln489_7_fu_748_p2;
                icmp_ln489_9_reg_1306 <= icmp_ln489_9_fu_905_p2;
                icmp_ln489_reg_1203 <= icmp_ln489_fu_202_p2;
                res_I_V_26_reg_1231 <= res_I_V_26_fu_394_p3;
                res_I_V_28_reg_1254 <= res_I_V_28_fu_551_p3;
                res_I_V_31_reg_1300 <= res_I_V_31_fu_865_p3;
                res_I_V_33_reg_1323 <= res_I_V_33_fu_1022_p3;
                res_I_V_reg_1277 <= res_I_V_fu_708_p3;
                sub_ln258_10_reg_1335 <= sub_ln258_10_fu_1068_p2;
                sub_ln258_2_reg_1243 <= sub_ln258_2_fu_440_p2;
                sub_ln258_4_reg_1266 <= sub_ln258_4_fu_597_p2;
                sub_ln258_6_reg_1289 <= sub_ln258_6_fu_754_p2;
                sub_ln258_8_reg_1312 <= sub_ln258_8_fu_911_p2;
                sub_ln258_reg_1220 <= sub_ln258_fu_274_p2;
                x_l_I_V_25_reg_1208 <= x_l_I_V_25_fu_230_p3;
                x_l_I_V_27_reg_1225 <= x_l_I_V_27_fu_386_p3;
                x_l_I_V_29_reg_1248 <= x_l_I_V_29_fu_543_p3;
                x_l_I_V_30_reg_1271 <= x_l_I_V_30_fu_700_p3;
                x_l_I_V_32_reg_1294 <= x_l_I_V_32_fu_857_p3;
                x_l_I_V_34_reg_1317 <= x_l_I_V_34_fu_1014_p3;
            end if;
        end if;
    end process;
    add_ln258_fu_208_p2 <= std_logic_vector(unsigned(zext_ln489_12_fu_198_p1) + unsigned(ap_const_lv3_7));
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter5 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state7_pp0_stage0_iter6 <= not((ap_const_boolean_1 = ap_const_boolean_1));
    ap_return <= 
        res_I_V_23_fu_1189_p2 when (p_Result_s_53_fu_1183_p2(0) = '1') else 
        res_I_V_35_fu_1163_p3;
    icmp_ln489_10_fu_980_p2 <= "1" when (unsigned(p_Result_28_fu_966_p4) < unsigned(zext_ln489_9_fu_976_p1)) else "0";
    icmp_ln489_11_fu_1062_p2 <= "1" when (unsigned(p_Result_31_fu_1048_p4) < unsigned(zext_ln489_10_fu_1058_p1)) else "0";
    icmp_ln489_12_fu_1121_p2 <= "1" when (unsigned(trunc_ln640_fu_1113_p1) < unsigned(zext_ln489_11_fu_1117_p1)) else "0";
    icmp_ln489_1_fu_268_p2 <= "1" when (unsigned(p_Result_5_fu_254_p4) < unsigned(zext_ln489_fu_264_p1)) else "0";
    icmp_ln489_2_fu_352_p2 <= "1" when (unsigned(p_Result_9_fu_338_p4) < unsigned(zext_ln489_1_fu_348_p1)) else "0";
    icmp_ln489_3_fu_434_p2 <= "1" when (unsigned(p_Result_1_fu_420_p4) < unsigned(zext_ln489_2_fu_430_p1)) else "0";
    icmp_ln489_4_fu_509_p2 <= "1" when (unsigned(p_Result_7_fu_495_p4) < unsigned(zext_ln489_3_fu_505_p1)) else "0";
    icmp_ln489_5_fu_591_p2 <= "1" when (unsigned(p_Result_13_fu_577_p4) < unsigned(zext_ln489_4_fu_587_p1)) else "0";
    icmp_ln489_6_fu_666_p2 <= "1" when (unsigned(p_Result_16_fu_652_p4) < unsigned(zext_ln489_5_fu_662_p1)) else "0";
    icmp_ln489_7_fu_748_p2 <= "1" when (unsigned(p_Result_19_fu_734_p4) < unsigned(zext_ln489_6_fu_744_p1)) else "0";
    icmp_ln489_8_fu_823_p2 <= "1" when (unsigned(p_Result_22_fu_809_p4) < unsigned(zext_ln489_7_fu_819_p1)) else "0";
    icmp_ln489_9_fu_905_p2 <= "1" when (unsigned(p_Result_25_fu_891_p4) < unsigned(zext_ln489_8_fu_901_p1)) else "0";
    icmp_ln489_fu_202_p2 <= "1" when (tmp_fu_188_p4 = ap_const_lv2_0) else "0";
    mul_I_V_fu_1171_p3 <= (ap_const_lv14_0 & res_I_V_35_fu_1163_p3);
    p_Result_12_fu_559_p4 <= res_I_V_28_fu_551_p3(13 downto 7);
    p_Result_13_fu_577_p4 <= x_l_I_V_29_fu_543_p3(22 downto 14);
    p_Result_15_fu_634_p4 <= res_I_V_29_fu_628_p3(13 downto 6);
    p_Result_16_fu_652_p4 <= x_l_I_V_fu_622_p3(21 downto 12);
    p_Result_18_fu_716_p4 <= res_I_V_fu_708_p3(13 downto 5);
    p_Result_19_fu_734_p4 <= x_l_I_V_30_fu_700_p3(20 downto 10);
    p_Result_1_fu_420_p4 <= x_l_I_V_27_fu_386_p3(24 downto 18);
    p_Result_21_fu_791_p4 <= res_I_V_30_fu_785_p3(13 downto 4);
    p_Result_22_fu_809_p4 <= x_l_I_V_31_fu_779_p3(19 downto 8);
    p_Result_24_fu_873_p4 <= res_I_V_31_fu_865_p3(13 downto 3);
    p_Result_25_fu_891_p4 <= x_l_I_V_32_fu_857_p3(18 downto 6);
    p_Result_27_fu_948_p4 <= res_I_V_32_fu_942_p3(13 downto 2);
    p_Result_28_fu_966_p4 <= x_l_I_V_33_fu_936_p3(17 downto 4);
    p_Result_30_fu_1030_p4 <= res_I_V_33_fu_1022_p3(13 downto 1);
    p_Result_31_fu_1048_p4 <= x_l_I_V_34_fu_1014_p3(16 downto 2);
    p_Result_38_fu_218_p5 <= (zext_ln712_fu_184_p1(29 downto 28) & sext_ln323_fu_214_p1 & zext_ln712_fu_184_p1(23 downto 0));
    p_Result_39_fu_287_p5 <= (x_l_I_V_25_reg_1208(29 downto 27) & sub_ln258_reg_1220 & x_l_I_V_25_reg_1208(21 downto 0));
    
    p_Result_40_fu_297_p4_proc : process(select_ln239_fu_280_p3)
    begin
        p_Result_40_fu_297_p4 <= select_ln239_fu_280_p3;
        p_Result_40_fu_297_p4(11) <= ap_const_lv1_1(0);
    end process;

    p_Result_41_fu_364_p5 <= (x_l_I_V_26_fu_307_p3(29 downto 26) & sub_ln258_1_fu_358_p2 & x_l_I_V_26_fu_307_p3(19 downto 0));
    
    p_Result_42_fu_376_p4_proc : process(res_I_V_25_fu_313_p3)
    begin
        p_Result_42_fu_376_p4 <= res_I_V_25_fu_313_p3;
        p_Result_42_fu_376_p4(10) <= ap_const_lv1_1(0);
    end process;

    p_Result_43_fu_446_p5 <= (x_l_I_V_27_reg_1225(29 downto 25) & sub_ln258_2_reg_1243 & x_l_I_V_27_reg_1225(17 downto 0));
    
    p_Result_44_fu_456_p4_proc : process(res_I_V_26_reg_1231)
    begin
        p_Result_44_fu_456_p4 <= res_I_V_26_reg_1231;
        p_Result_44_fu_456_p4(9) <= ap_const_lv1_1(0);
    end process;

    p_Result_45_fu_521_p5 <= (x_l_I_V_28_fu_465_p3(29 downto 24) & sub_ln258_3_fu_515_p2 & x_l_I_V_28_fu_465_p3(15 downto 0));
    
    p_Result_46_fu_533_p4_proc : process(res_I_V_27_fu_471_p3)
    begin
        p_Result_46_fu_533_p4 <= res_I_V_27_fu_471_p3;
        p_Result_46_fu_533_p4(8) <= ap_const_lv1_1(0);
    end process;

    p_Result_47_fu_603_p5 <= (x_l_I_V_29_reg_1248(29 downto 23) & sub_ln258_4_reg_1266 & x_l_I_V_29_reg_1248(13 downto 0));
    
    p_Result_48_fu_613_p4_proc : process(res_I_V_28_reg_1254)
    begin
        p_Result_48_fu_613_p4 <= res_I_V_28_reg_1254;
        p_Result_48_fu_613_p4(7) <= ap_const_lv1_1(0);
    end process;

    p_Result_49_fu_678_p5 <= (x_l_I_V_fu_622_p3(29 downto 22) & sub_ln258_5_fu_672_p2 & x_l_I_V_fu_622_p3(11 downto 0));
    
    p_Result_50_fu_690_p4_proc : process(res_I_V_29_fu_628_p3)
    begin
        p_Result_50_fu_690_p4 <= res_I_V_29_fu_628_p3;
        p_Result_50_fu_690_p4(6) <= ap_const_lv1_1(0);
    end process;

    p_Result_51_fu_760_p5 <= (x_l_I_V_30_reg_1271(29 downto 21) & sub_ln258_6_reg_1289 & x_l_I_V_30_reg_1271(9 downto 0));
    
    p_Result_52_fu_770_p4_proc : process(res_I_V_reg_1277)
    begin
        p_Result_52_fu_770_p4 <= res_I_V_reg_1277;
        p_Result_52_fu_770_p4(5) <= ap_const_lv1_1(0);
    end process;

    p_Result_53_fu_835_p5 <= (x_l_I_V_31_fu_779_p3(29 downto 20) & sub_ln258_7_fu_829_p2 & x_l_I_V_31_fu_779_p3(7 downto 0));
    
    p_Result_54_fu_847_p4_proc : process(res_I_V_30_fu_785_p3)
    begin
        p_Result_54_fu_847_p4 <= res_I_V_30_fu_785_p3;
        p_Result_54_fu_847_p4(4) <= ap_const_lv1_1(0);
    end process;

    p_Result_55_fu_917_p5 <= (x_l_I_V_32_reg_1294(29 downto 19) & sub_ln258_8_reg_1312 & x_l_I_V_32_reg_1294(5 downto 0));
    
    p_Result_56_fu_927_p4_proc : process(res_I_V_31_reg_1300)
    begin
        p_Result_56_fu_927_p4 <= res_I_V_31_reg_1300;
        p_Result_56_fu_927_p4(3) <= ap_const_lv1_1(0);
    end process;

    p_Result_57_fu_992_p5 <= (x_l_I_V_33_fu_936_p3(29 downto 18) & sub_ln258_9_fu_986_p2 & x_l_I_V_33_fu_936_p3(3 downto 0));
    
    p_Result_58_fu_1004_p4_proc : process(res_I_V_32_fu_942_p3)
    begin
        p_Result_58_fu_1004_p4 <= res_I_V_32_fu_942_p3;
        p_Result_58_fu_1004_p4(2) <= ap_const_lv1_1(0);
    end process;

    p_Result_59_fu_1074_p5 <= (x_l_I_V_34_reg_1317(29 downto 17) & sub_ln258_10_reg_1335 & x_l_I_V_34_reg_1317(1 downto 0));
    p_Result_5_fu_254_p4 <= x_l_I_V_25_fu_230_p3(26 downto 22);
    
    p_Result_60_fu_1084_p4_proc : process(res_I_V_33_reg_1323)
    begin
        p_Result_60_fu_1084_p4 <= res_I_V_33_reg_1323;
        p_Result_60_fu_1084_p4(1) <= ap_const_lv1_1(0);
    end process;

    p_Result_61_fu_1133_p5 <= (x_l_I_V_35_fu_1093_p3(29 downto 16) & sub_ln258_11_fu_1127_p2);
    
    p_Result_62_fu_1145_p4_proc : process(res_I_V_34_fu_1099_p3)
    begin
        p_Result_62_fu_1145_p4 <= res_I_V_34_fu_1099_p3;
        p_Result_62_fu_1145_p4(0) <= ap_const_lv1_1(0);
    end process;

    p_Result_6_fu_477_p4 <= res_I_V_27_fu_471_p3(13 downto 8);
    p_Result_7_fu_495_p4 <= x_l_I_V_28_fu_465_p3(23 downto 16);
    p_Result_8_fu_320_p4 <= res_I_V_25_fu_313_p3(13 downto 10);
    p_Result_9_fu_338_p4 <= x_l_I_V_26_fu_307_p3(25 downto 20);
    p_Result_s_53_fu_1183_p2 <= "1" when (unsigned(x_l_I_V_36_fu_1155_p3) > unsigned(zext_ln717_fu_1179_p1)) else "0";
    p_Result_s_fu_402_p4 <= res_I_V_26_fu_394_p3(13 downto 9);
    res_I_V_23_fu_1189_p2 <= std_logic_vector(unsigned(res_I_V_35_fu_1163_p3) + unsigned(ap_const_lv14_1));
    res_I_V_25_fu_313_p3 <= 
        select_ln239_fu_280_p3 when (icmp_ln489_1_reg_1214(0) = '1') else 
        p_Result_40_fu_297_p4;
    res_I_V_26_fu_394_p3 <= 
        res_I_V_25_fu_313_p3 when (icmp_ln489_2_fu_352_p2(0) = '1') else 
        p_Result_42_fu_376_p4;
    res_I_V_27_fu_471_p3 <= 
        res_I_V_26_reg_1231 when (icmp_ln489_3_reg_1237(0) = '1') else 
        p_Result_44_fu_456_p4;
    res_I_V_28_fu_551_p3 <= 
        res_I_V_27_fu_471_p3 when (icmp_ln489_4_fu_509_p2(0) = '1') else 
        p_Result_46_fu_533_p4;
    res_I_V_29_fu_628_p3 <= 
        res_I_V_28_reg_1254 when (icmp_ln489_5_reg_1260(0) = '1') else 
        p_Result_48_fu_613_p4;
    res_I_V_30_fu_785_p3 <= 
        res_I_V_reg_1277 when (icmp_ln489_7_reg_1283(0) = '1') else 
        p_Result_52_fu_770_p4;
    res_I_V_31_fu_865_p3 <= 
        res_I_V_30_fu_785_p3 when (icmp_ln489_8_fu_823_p2(0) = '1') else 
        p_Result_54_fu_847_p4;
    res_I_V_32_fu_942_p3 <= 
        res_I_V_31_reg_1300 when (icmp_ln489_9_reg_1306(0) = '1') else 
        p_Result_56_fu_927_p4;
    res_I_V_33_fu_1022_p3 <= 
        res_I_V_32_fu_942_p3 when (icmp_ln489_10_fu_980_p2(0) = '1') else 
        p_Result_58_fu_1004_p4;
    res_I_V_34_fu_1099_p3 <= 
        res_I_V_33_reg_1323 when (icmp_ln489_11_reg_1329(0) = '1') else 
        p_Result_60_fu_1084_p4;
    res_I_V_35_fu_1163_p3 <= 
        res_I_V_34_fu_1099_p3 when (icmp_ln489_12_fu_1121_p2(0) = '1') else 
        p_Result_62_fu_1145_p4;
    res_I_V_fu_708_p3 <= 
        res_I_V_29_fu_628_p3 when (icmp_ln489_6_fu_666_p2(0) = '1') else 
        p_Result_50_fu_690_p4;
    select_ln239_fu_280_p3 <= 
        ap_const_lv14_0 when (icmp_ln489_reg_1203(0) = '1') else 
        ap_const_lv14_1000;
    select_ln489_fu_238_p3 <= 
        ap_const_lv2_0 when (icmp_ln489_fu_202_p2(0) = '1') else 
        ap_const_lv2_2;
        sext_ln323_fu_214_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln258_fu_208_p2),4));

    sub_ln258_10_fu_1068_p2 <= std_logic_vector(unsigned(p_Result_31_fu_1048_p4) - unsigned(zext_ln489_10_fu_1058_p1));
    sub_ln258_11_fu_1127_p2 <= std_logic_vector(unsigned(trunc_ln640_fu_1113_p1) - unsigned(zext_ln489_11_fu_1117_p1));
    sub_ln258_1_fu_358_p2 <= std_logic_vector(unsigned(p_Result_9_fu_338_p4) - unsigned(zext_ln489_1_fu_348_p1));
    sub_ln258_2_fu_440_p2 <= std_logic_vector(unsigned(p_Result_1_fu_420_p4) - unsigned(zext_ln489_2_fu_430_p1));
    sub_ln258_3_fu_515_p2 <= std_logic_vector(unsigned(p_Result_7_fu_495_p4) - unsigned(zext_ln489_3_fu_505_p1));
    sub_ln258_4_fu_597_p2 <= std_logic_vector(unsigned(p_Result_13_fu_577_p4) - unsigned(zext_ln489_4_fu_587_p1));
    sub_ln258_5_fu_672_p2 <= std_logic_vector(unsigned(p_Result_16_fu_652_p4) - unsigned(zext_ln489_5_fu_662_p1));
    sub_ln258_6_fu_754_p2 <= std_logic_vector(unsigned(p_Result_19_fu_734_p4) - unsigned(zext_ln489_6_fu_744_p1));
    sub_ln258_7_fu_829_p2 <= std_logic_vector(unsigned(p_Result_22_fu_809_p4) - unsigned(zext_ln489_7_fu_819_p1));
    sub_ln258_8_fu_911_p2 <= std_logic_vector(unsigned(p_Result_25_fu_891_p4) - unsigned(zext_ln489_8_fu_901_p1));
    sub_ln258_9_fu_986_p2 <= std_logic_vector(unsigned(p_Result_28_fu_966_p4) - unsigned(zext_ln489_9_fu_976_p1));
    sub_ln258_fu_274_p2 <= std_logic_vector(unsigned(p_Result_5_fu_254_p4) - unsigned(zext_ln489_fu_264_p1));
    tmp_10_fu_1040_p3 <= (p_Result_30_fu_1030_p4 & ap_const_lv1_1);
    tmp_11_fu_1105_p3 <= (res_I_V_34_fu_1099_p3 & ap_const_lv1_1);
    tmp_1_fu_958_p3 <= (p_Result_27_fu_948_p4 & ap_const_lv1_1);
    tmp_2_fu_246_p3 <= (select_ln489_fu_238_p3 & ap_const_lv1_1);
    tmp_3_fu_330_p3 <= (p_Result_8_fu_320_p4 & ap_const_lv1_1);
    tmp_4_fu_412_p3 <= (p_Result_s_fu_402_p4 & ap_const_lv1_1);
    tmp_5_fu_487_p3 <= (p_Result_6_fu_477_p4 & ap_const_lv1_1);
    tmp_6_fu_569_p3 <= (p_Result_12_fu_559_p4 & ap_const_lv1_1);
    tmp_7_fu_644_p3 <= (p_Result_15_fu_634_p4 & ap_const_lv1_1);
    tmp_8_fu_726_p3 <= (p_Result_18_fu_716_p4 & ap_const_lv1_1);
    tmp_9_fu_801_p3 <= (p_Result_21_fu_791_p4 & ap_const_lv1_1);
    tmp_fu_188_p4 <= x_int_reg(25 downto 24);
    tmp_s_fu_883_p3 <= (p_Result_24_fu_873_p4 & ap_const_lv1_1);
    trunc_ln640_fu_1113_p1 <= x_l_I_V_35_fu_1093_p3(16 - 1 downto 0);
    x_l_I_V_25_fu_230_p3 <= 
        zext_ln712_fu_184_p1 when (icmp_ln489_fu_202_p2(0) = '1') else 
        p_Result_38_fu_218_p5;
    x_l_I_V_26_fu_307_p3 <= 
        x_l_I_V_25_reg_1208 when (icmp_ln489_1_reg_1214(0) = '1') else 
        p_Result_39_fu_287_p5;
    x_l_I_V_27_fu_386_p3 <= 
        x_l_I_V_26_fu_307_p3 when (icmp_ln489_2_fu_352_p2(0) = '1') else 
        p_Result_41_fu_364_p5;
    x_l_I_V_28_fu_465_p3 <= 
        x_l_I_V_27_reg_1225 when (icmp_ln489_3_reg_1237(0) = '1') else 
        p_Result_43_fu_446_p5;
    x_l_I_V_29_fu_543_p3 <= 
        x_l_I_V_28_fu_465_p3 when (icmp_ln489_4_fu_509_p2(0) = '1') else 
        p_Result_45_fu_521_p5;
    x_l_I_V_30_fu_700_p3 <= 
        x_l_I_V_fu_622_p3 when (icmp_ln489_6_fu_666_p2(0) = '1') else 
        p_Result_49_fu_678_p5;
    x_l_I_V_31_fu_779_p3 <= 
        x_l_I_V_30_reg_1271 when (icmp_ln489_7_reg_1283(0) = '1') else 
        p_Result_51_fu_760_p5;
    x_l_I_V_32_fu_857_p3 <= 
        x_l_I_V_31_fu_779_p3 when (icmp_ln489_8_fu_823_p2(0) = '1') else 
        p_Result_53_fu_835_p5;
    x_l_I_V_33_fu_936_p3 <= 
        x_l_I_V_32_reg_1294 when (icmp_ln489_9_reg_1306(0) = '1') else 
        p_Result_55_fu_917_p5;
    x_l_I_V_34_fu_1014_p3 <= 
        x_l_I_V_33_fu_936_p3 when (icmp_ln489_10_fu_980_p2(0) = '1') else 
        p_Result_57_fu_992_p5;
    x_l_I_V_35_fu_1093_p3 <= 
        x_l_I_V_34_reg_1317 when (icmp_ln489_11_reg_1329(0) = '1') else 
        p_Result_59_fu_1074_p5;
    x_l_I_V_36_fu_1155_p3 <= 
        x_l_I_V_35_fu_1093_p3 when (icmp_ln489_12_fu_1121_p2(0) = '1') else 
        p_Result_61_fu_1133_p5;
    x_l_I_V_fu_622_p3 <= 
        x_l_I_V_29_reg_1248 when (icmp_ln489_5_reg_1260(0) = '1') else 
        p_Result_47_fu_603_p5;
    zext_ln489_10_fu_1058_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_10_fu_1040_p3),15));
    zext_ln489_11_fu_1117_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_11_fu_1105_p3),16));
    zext_ln489_12_fu_198_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_fu_188_p4),3));
    zext_ln489_1_fu_348_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_3_fu_330_p3),6));
    zext_ln489_2_fu_430_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_4_fu_412_p3),7));
    zext_ln489_3_fu_505_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_5_fu_487_p3),8));
    zext_ln489_4_fu_587_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_6_fu_569_p3),9));
    zext_ln489_5_fu_662_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_7_fu_644_p3),10));
    zext_ln489_6_fu_744_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_8_fu_726_p3),11));
    zext_ln489_7_fu_819_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_9_fu_801_p3),12));
    zext_ln489_8_fu_901_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_s_fu_883_p3),13));
    zext_ln489_9_fu_976_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_1_fu_958_p3),14));
    zext_ln489_fu_264_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_2_fu_246_p3),5));
    zext_ln712_fu_184_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(x_int_reg),30));
    zext_ln717_fu_1179_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mul_I_V_fu_1171_p3),30));
end behav;
