webtalk_init -webtalk_dir /mnt/shared/Linux/gdrive/usm/2021-s2/ipd432/repo/tarea_1/fsm/fsm.sim/sim_1/behav/xsim/xsim.dir/FSM_sim_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sat Oct 30 04:18:27 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2021.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3247384" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "23c0751a-9c7d-426c-8c47-981c229f68f5" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "0c164a7f36f04848945742eb2e080692" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "11" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Elementary" -context "user_environment"
webtalk_add_data -client project -key os_release -value "elementary OS 6 Odin" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 5 3600X 6-Core Processor" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2791.961 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "2" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.04_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "116972_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3438405744 -regid "" -xml /mnt/shared/Linux/gdrive/usm/2021-s2/ipd432/repo/tarea_1/fsm/fsm.sim/sim_1/behav/xsim/xsim.dir/FSM_sim_behav/webtalk/usage_statistics_ext_xsim.xml -html /mnt/shared/Linux/gdrive/usm/2021-s2/ipd432/repo/tarea_1/fsm/fsm.sim/sim_1/behav/xsim/xsim.dir/FSM_sim_behav/webtalk/usage_statistics_ext_xsim.html -wdm /mnt/shared/Linux/gdrive/usm/2021-s2/ipd432/repo/tarea_1/fsm/fsm.sim/sim_1/behav/xsim/xsim.dir/FSM_sim_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
